# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/mbrandone/Desktop/2015Year/ELEN232/Project_6/Problem_6/Problem_6.cache/wt [current_project]
set_property parent.project_path /home/mbrandone/Desktop/2015Year/ELEN232/Project_6/Problem_6/Problem_6.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  /home/mbrandone/Desktop/2015Year/ELEN232/Project_6/Problem_6/Problem_6.srcs/sources_1/new/bitAdder.v
  /home/mbrandone/Desktop/2015Year/ELEN232/Project_6/Problem_6/Problem_6.srcs/sources_1/new/fourBitRCA.v
  /home/mbrandone/Desktop/2015Year/ELEN232/Project_6/Problem_6/Problem_6.srcs/sources_1/new/eightBitRCA.v
}
synth_design -top eightBitRCA -part xc7a35tcpg236-1
write_checkpoint -noxdef eightBitRCA.dcp
catch { report_utilization -file eightBitRCA_utilization_synth.rpt -pb eightBitRCA_utilization_synth.pb }
