# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/mbrandone/Desktop/2015Year/ELEN232/project_4/project_4.cache/wt [current_project]
set_property parent.project_path /home/mbrandone/Desktop/2015Year/ELEN232/project_4/project_4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  /home/mbrandone/Desktop/2015Year/ELEN232/project_4/project_4.srcs/sources_1/new/Problem_3.v
  /home/mbrandone/Desktop/2015Year/ELEN232/project_4/project_4.srcs/sources_1/new/Problem_2.v
  /home/mbrandone/Desktop/2015Year/ELEN232/project_4/project_4.srcs/sources_1/new/Problem_1.v
  /home/mbrandone/Desktop/2015Year/ELEN232/project_4/project_4.srcs/sources_1/new/1bitComp.v
  /home/mbrandone/Desktop/2015Year/ELEN232/project_4/project_4.srcs/sources_1/new/Problem_4.v
}
read_xdc /home/mbrandone/Desktop/2015Year/ELEN232/project_4/project_4.srcs/constrs_1/new/Problem_1_constraints.xdc
set_property used_in_implementation false [get_files /home/mbrandone/Desktop/2015Year/ELEN232/project_4/project_4.srcs/constrs_1/new/Problem_1_constraints.xdc]

read_xdc /home/mbrandone/Desktop/2015Year/ELEN232/project_4/project_4.srcs/constrs_1/new/Problem_3_constraints.xdc
set_property used_in_implementation false [get_files /home/mbrandone/Desktop/2015Year/ELEN232/project_4/project_4.srcs/constrs_1/new/Problem_3_constraints.xdc]

synth_design -top Problem_3 -part xc7a35tcpg236-1
write_checkpoint -noxdef Problem_3.dcp
catch { report_utilization -file Problem_3_utilization_synth.rpt -pb Problem_3_utilization_synth.pb }
